### ISSUE TITLE
Change to using Froala WYSIWYG Editor

### ISSUE THREAD

**Issue by EGreg** [EGreg/Platform-history#18]
In the `Streams/html` tool, retain support for CKEditor, but change to this one by default. It's less obtrusive and works on mobile as well!

Make an option called `editor` and possible values 'CKEDITOR' and 'Froala' (default).

Please try to make the changes as clean as possible. Push the changes into your fork of Q and submit a pull request.

http://editor.froala.com/#editor-example

**Comment by EGreg** [comment]
Let's make a branch called feature/froala and check it in. When it's done I will merge it into master.

**Comment by tigranbs** [comment]
Ok.  
I'll do it tomorrow. Today I must finish some important parts of my project , investors want to see it.

-----Original Message-----

**Comment by glebv** [comment]
Грег, я сегодня ничего не делал, у нас разговор так и остался подвисшим,
жду от тебя инструкции.

On Fri, Jun 13, 2014 at 5:00 PM, Gregory Magarshak <notifications@github.com

> wrote:
> 
> Let's make a branch called feature/froala and check it in. When it's done
> I will merge it into master.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EGreg/Q/issues/18#issuecomment-46014277.

## 

Best regards,
Gleb Vinnikov

Это электронное сообщение может содержать конфиденциальную
информацию,  которая  предназначена  для  адресата  и  не  может  быть
сообщена  или  передана  третьим лицам. В случае, если письмо попало к
Вам  по  ошибке  -  пожалуйста,  сообщите  нам о факте его получения и
уничтожьте его.

**Comment by EGreg** [comment]
We implemented it!
