### ISSUE TITLE
Finish the Q/viewport tool

### ISSUE THREAD

**Issue by EGreg** [EGreg/Platform-history#27]
Most of our [tools](http://platform.qbix.com/guide/tools) are supposed to be placed on pages with minimal fuss, and work in `desktop`, `tablet` and `mobile` environments.

In particular, the `Q/viewport` tool is supposed to be used to resize and drag things around inside a container element. I have already somewhat implemented it on the desktop -- but the functionality needs to be finished, and also support mobile.
#### ZOOM

Here, the mouse wheel scrolling up is supposed to zoom in, and mouse wheel scrolling down would zoom out. Q already provides the `Q.Pointer.wheel` event, which the current implementation of `Q/viewport` uses. But, the zoom is supposed to actually zoom towards the point that the user is pointing. Your challenge is to figure out the math for this (you can also look up what [other people did](http://stackoverflow.com/questions/2916081/zoom-in-on-a-point-using-scale-and-translate) and adapt it). The other challenge is to make sure it works on all browsers. I have already normalized it so that we use `zoom` CSS property in IE, and the `-moz-transform` stuff has origin in `(0, 0)` so it can mimic `zoom` and the math can be the same in both cases.
#### DRAG

The user is supposed to be able to drag things around, with the _constraint_ that the contents should always completely cover the viewport. That is, after calculating the coordinates, you will have to check if the `left` of the content is > 0, and if so, set `left = 0`, and likewise if the `right` of the _zoomed_ content > the viewport width, you have to move it to the left by enough pixels to make sure the `right` is now equal to the viewport width. In short ... do not let the boundary outside the content to be displayed in the viewport.
### TOUCHSCREEN

Here you can simply test `Q.info.isTouchscreen` in JS and `html.Q_isTouchscreen` in CSS. If we have a touchscreen, then
#### ZOOM

Instead of a scroll wheel, you should have the image be zoomed using two fingers. The math here is even more complex than the scrollwheel because the contents should be resized in such a way that the position of the first finger relative to the contents does not change (i.e. if the finger is moved, the content is moved so that the point remains underneath the finger) while the position of the second finger should change by the minimum amount (i.e. if the second finger is moved, the content should be moved & resized so that the first finger constraint is satisfied AND the aspect ratio width/height of the content isn't distorted AND the second finger is as close as possible to its original position in the content). Positions "in the content" can be expressed as pairs `{x: x, y: y}` where `x` and `y` are fractions between 0 and 1.

Probably the easiest way to achieve this algorithm is to see how much the distance between the two fingers changes, and increase the zoom by that much. And then move the image so that the first finger is still relatively in the same position as when it was pressed down. Yes, this is probably the most straightforward way.

Maybe you can find [existing code online](https://github.com/HotStudio/touchy) that does this, but 
#### DRAG

The drag is the same as on the desktop, but performed with a finger. Look at `Q.Pointer.touchCount` and other methods of `Q.Pointer` to help you figure out how many fingers are on the screen, and when something is moved. Otherwise, the constraints are exactly the same, and the same function can be used for both desktop and mobile implementations.
### Cleaning up

PS: Usually, there are [ways](http://platform.qbix.com/guide/tools#events) to add listeners to events that are removed when the Q tool is removed. However, here we are actually making a jQuery plugin, which can be removed at any time. Q doesn't yet support auto-removing event listeners in this case, so for now, you will have to implement a `destroy` method on the plugin, which would remove the event listeners manually and return it to the state it was in before the plugin was applied.

**Comment by EGreg** [comment]
OK I admit it took me about 4 hours but I did it: https://github.com/EGreg/Q/commit/c16d4231dc2e845539c02a11d6acb034e6eb036f

**Comment by EGreg** [comment]
1. scale should refuse to make content element smaller than viewport (width or height)
2. fixPosition should happen after scale, I think it already does
3. allow zooming <= 1 subject to above constraints
4. implement "initial" option, to show initial viewport location relative to content element
5. replace "wrap" option with detection of existing container and stretcher ... if it exists with the right classes, then no need to create one
   http://api.jquery.com/wrap/ http://api.jquery.com/unwrap/
   optional: on "remove" method, you can unwrap if you wrapped earlier
6. onRelease and result
   $(element).state("Q/viewport").result.left
   implement "onReleaseWheelTimeout" in milliseconds, with default = 300
7. minimumResultSize: {width:   ,     height:      }

**Comment by glebv** [comment]
all points are done, closed
