### ISSUE TITLE
Switch from Mustache to Handlebars

### ISSUE THREAD

**Issue by EGreg** [EGreg/Platform-history#36]
Add Handlebars to the project, leaving Mustache there just in case.

Everywhere we use Mustache now, we can switch to using Handlebars.

For PHP: https://github.com/mardix/Handlebars
For JS: http://handlebarsjs.com/

Carefully look in the code for "mustache" and change all uses to handlebars. Change the default from mustache to handlebars. Remember to also change the file names ending in .mustache, converting them to handlebars.

Don't worry -- handlebars can read mustache files.

**Comment by tigranbs** [comment]
Switched , but not tested node.js and client side javascript .... futures/Handlebars branch

**Comment by tigranbs** [comment]
I've tested and pushed final changes to futures/Handlebars branch ...
The only thing is Q.url('plugins/Q/js/handlebars.js') (at platforms/plugins/Q/web/Q.js 6967 line) gives wrong url with that relative path, but when I'm typing for example http://qapp.loc/plugins/Q/js/handlebars.js  it works fine.
I saw that in Q.url function Q.baseUrl is undefined , maybe there's the problem ....

**Comment by EGreg** [comment]
Do you mean Q.info.baseUrl is undefined?

Your app sets it in local/app.json

On Monday, July 28, 2014, Tigran Bayburtsyan (Platon) <
notifications@github.com> wrote:

> I've tested and pushed final changes to futures/Handlebars branch ...
> The only thing is Q.url('plugins/Q/js/handlebars.js') (at
> platforms/plugins/Q/web/Q.js 6967 line) gives wrong url with that relative
> path, but when I'm typing for example
> http://qapp.loc/plugins/Q/js/handlebars.js it works fine.
> I saw that in Q.url function Q.baseUrl is undefined , maybe there's the
> problem ....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EGreg/Q/issues/36#issuecomment-50318073.

## 

Sincerely,
Greg Magarshak
CEO, Qbix Inc.                         http://qbix.com
